### ISSUE TITLE
Use "cbmbasic" command as tokenizer

### ISSUE THREAD

**Issue by sblendorio** [mist64/cbmbasic#3]
is it possible to use cbmbasic to transform an ASCII file into a .PRG, tokenized file, ready-to-run on a C64?

**Comment by mist64** [comment]
Sure, paste it into cbmbasic, making sure the keywords are upper case, and type
    SAVE“filename.prg“
to write the tokenized version to disk. Similarly, you can detokenize a .prg using LOAD and LIST.

**Comment by daitangio** [comment]
Very interesting feature.
I suggest to stress it in the README
